### ISSUE TITLE
Govee Bluetooth Meat Thermometer Support

### ISSUE THREAD

**Issue by nphil** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#14]
I have a feature request to add support for [this](https://smile.amazon.com/dp/B08317TDP1/ref=emc_b_5_t) product if possible!

**Comment by Thrilleratplay** [comment]
Sorry, this too different of a device and would not be compatible with the supported Thermometer/Hygrometers.

Just curious, how would you use a meat thermometer with Home Assistant?  Unless you run a BBQ joint, Integrating alerts for something that would not always bee connected seems like more of a hassle than its worth (at least to me it does).

**Comment by nphil** [comment]
@Thrilleratplay No worries, just thought I'd throw it out as your integration works really well with the Hygrometers. My main intention was to get alerts (with pushover + google cast announcements) when a set temperature was reached without relying on keeping the govee app opened (or even installed for that matter).
