### ISSUE TITLE
H5101 Sensor

### ISSUE THREAD

**Issue by XenoLight** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#22]
What would you need to be able to add this sensor. I have two and it is bluetooth as well, I have a raspberry pi setup, with python exposure ( just cloud related is all ), so if there is any methodology or approach to figure it out im down to try myself, just not sure where to start.

**Comment by Thrilleratplay** [comment]
At very least, examples of the HCI packets it emits.  #16  should give a basic example.  Out of curiosity, have you tried it already?  Looking at the FCC docs, the chips look identical between the H5101 and H5102, mainly the battery type and bluetooth power seem to be only differences.

**Comment by photinus** [comment]
They work as is, just got two of them and they work like a charm.

**Comment by Thrilleratplay** [comment]
@photinus Sweet.
