### ISSUE TITLE
[FEATURE] Assign device to AREA

### ISSUE THREAD

**Issue by Cyber5imon** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#23]
One nice feature in HA is the ability to define areas that contain your devices. Most commonly this is used to setup rooms in your house. You might have areas for Kitchen, Living Room, Dining Room, Hallway, Master Bedroom, Spare Bedroom, etc...

![HA-AreaExample](https://user-images.githubusercontent.com/2486134/95479612-f78e4400-0958-11eb-8276-5a3c0035a905.png)

It doesn't appear there is any way to assign govee devices to areas. From what I gather, the main issue is that govee devices aren't actually added to HA as devices at all. Rather, they are entities, and entities can not be assigned an area. To make this custom integration more "compatible" with HA, it seems each device should be added to HA as a device, and then that device should contain the temperature and humidity entities. This seems to be how other integrations work.

![HA-AddtoArea](https://user-images.githubusercontent.com/2486134/95479914-4dfb8280-0959-11eb-9591-22ffe6e6ad39.png)

Having only started using HA a couple of months ago, I'm not familiar enough with it's underpinnings to effectively code this change, however if someone is willing to point me in the right direction, I would be happy to try and tackle this additional functionality and once I have it working add the pull request.

Hopefully we can make this happen as areas are a very effective way to manage devices!

**Comment by Thrilleratplay** [comment]
From everything I have read, it is not possible to assign an entity to an area and is a limitation of Home Assistant.  If this is incorrect or changes, please let me know.

**Comment by Cyber5imon** [comment]
Correct, however can't the govee devices be added to HA as devices and then temperature and humidity be entities of each device? I believe this is how most other integrations/components operate.

**Comment by Cyber5imon** [comment]
[rospogrigio/localtuya-homeassistant](https://github.com/rospogrigio/localtuya-homeassistant) is an example of a custom component that creates devices and then adds the temperature and humidity of each device as entities.

**Comment by Thrilleratplay** [comment]
That is because that is an integration which is an underlying platform that can allow different devices to communicate, such a zwave and zigbee.  This is a sensor.  While it would be nice to be able to unify generic sensors into a n integration, that is beyond the scope of this component and hopefully something Home Assistant will address as it have been confusing for a long time.  Sorry.
