### ISSUE TITLE
Passive BLE monitor integration (Xiaomi Mijia BLE MiBeacon monitor) syntax change. 

### ISSUE THREAD

**Issue by lcoppenr** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#26]
The BLE Monitor integration changed the syntax of the Configuration.yaml file.  I'm confused how to get the Govee sensors working again.

My syntax  guess, which isn't working:
 ble_monitor:
  - platform: govee_ble_hci
    govee_devices:
        - mac: "xxxxxxxxxxxxxxx"
          name: NoIdeaGovee1
        - mac: "xxxxxxxxxxxxxxx"
          name: NoIdeaGovee2

Any help would be greatly appreciated.

**Comment by Thrilleratplay** [comment]
Another component changed the config file?  If your config file has issues, first use the "Check Home Assistant configuration" component, which should be built into Home Assistant.  Beyond that, logs will be useful.

Additionally, this component is for Govee devices, and will not work with Xiaomi devices.

**Comment by lcoppenr** [comment]
They component had an update that changed its syntax (I had to edit config manually).  It appears to have caused issues on the bottom of my configuration where govee_ble_hci was.  

Thx for the quick reply.  My problem had nothing to do with govee_ble_hci.

**Comment by Thrilleratplay** [comment]
Ok.  It sounds like you resolved your issue.  If you have any more issues or questions, please use the [Home Assistant community post for this component](https://community.home-assistant.io/t/govee-ble-thermometer-hygrometer-sensor/166696)
