### ISSUE TITLE
Works with H5177

### ISSUE THREAD

**Issue by zpatten** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#28]
Just wanted to report that I'm using this with the Govee H5177 and it seems to be working perfect.

![image](https://user-images.githubusercontent.com/670610/104850471-ee483800-58b4-11eb-875b-3c13063d3a11.png)

- https://www.amazon.com/gp/product/B08C9VYMHY

**Comment by Thrilleratplay** [comment]
@zpatten Great.  Thank you.

EDIT: I realized I had ordered one of these and forgot to test it.  If any issues do come up, I will be able to debug them.
