### ISSUE TITLE
HASS receives state changes many times per period

### ISSUE THREAD

**Issue by sfjes** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#3]
Home Assistant is getting updated with a new state change for every message that contains valid data, which results in 3-20 state changes per period. With a 60 second period, I've accumulated 27k+ state changes in Home Assistant in the last 48 hours (per sensor, temp and humid each).

Among other things it's noticeable by slower graph generation.

**Comment by sfjes** [comment]
Created a PR to fix it. Not too familiar with HA or python conventions, but it works for me.

https://github.com/Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci/pull/4

**Comment by Thrilleratplay** [comment]
Merged in.  Thank you.
