### ISSUE TITLE
Not Work on Doker ?

### ISSUE THREAD

**Issue by cenzo85** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#31]
Hi, I have correctly configure it in Hassio the Govee H5075. The temperature and the humidity arrive in perfectly :) 
but...after some time, I have decided to install Home Assitant by docket on the Raspberry OS.
After the same operations I not receive anyting ...

....there are some differente cnfiguration to apply ?

**Comment by Thrilleratplay** [comment]
Responding on community page
