### ISSUE TITLE
Error doing job: Future exception was never retrieved

### ISSUE THREAD

**Issue by keezppc** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#32]
I get the below error after restarting HA and the sensors show as unavailable.  I'm using a USB Bluetooth dongle connected via USB Extension Cable.

Running Home Assistant OS 5.12 on a RPi4.

This is my first time reporting an issue like this so I'm not sure I'm providing everything that would help.  Let me know if more information is needed.

Logger: homeassistant
Source: custom_components/govee_ble_hci/sensor.py:190 
First occurred: 7:44:53 PM (1 occurrences) 
Last logged: 7:44:53 PM

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/govee_ble_hci/sensor.py", line 190, in update_ble_loop
    adapter.start_scanning()
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 276, in start_scanning
    self.set_scan_enable(False)
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 132, in set_scan_enable
    self.write_buffer(cmd)
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 51, in write_buffer
    self._socket.send(data)
OSError: [Errno 100] Network is down

This is my config

  - platform: govee_ble_hci
    rounding: True
    decimals: 1
    period: 60
    log_spikes: False
    hci_device: hci0
    govee_devices:
      - mac: "A4:C1:38:A0:22:F4"
        name: ****
      - mac: "A4:C1:38:15:FD:F9"
        name: ****
      - mac: "A4:C1:38:97:EF:47"
        name: ****

**Comment by Thrilleratplay** [comment]
As stated in the README, any questions or support should be asked on [this component's Home Assistant community post](https://community.home-assistant.io/t/govee-ble-thermometer-hygrometer-sensor/166696).  On an rPi, the internal bluetooth adapter will likely be `hci_device: hci0`, try changing this to `hci_device: hci1`, place at least one of the thermometers next to the device to ensure they are not out of range and try rebooting the rPi.  If this does not fix the issue, please continue on the discussion on the community forum.

**Comment by keezppc** [comment]
Thank you for the suggestions.  My apologies for posting in the wrong place.
