### ISSUE TITLE
No version number in manifest file

### ISSUE THREAD

**Issue by bens0n** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#33]
When loading this integration into HA 2021.03.0, the following message is reported on startup:
> No 'version' key in the manifest file for custom integration 'govee_ble_hci'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'govee_ble_hci'

**Comment by Thrilleratplay** [comment]
Thank you for letting me know.  It looks like just one line needs to be added and should have this deployed soon.

**Comment by bens0n** [comment]
Thank you. I should have said originally, thank you for your work on this - the integration is literally in use constantly at this end!

**Comment by bens0n** [comment]
Sorry for the open / close !

**Comment by Thrilleratplay** [comment]
Should be all set.  Thanks again for letting me know, I don't normally look at my logs unless something is wrong.

**Comment by SteveOnorato** [comment]
In case you want to be automatically alerted of these types of things in the future, you can have github run hassfest daily: https://developers.home-assistant.io/blog/2020/04/16/hassfest/
Takes about 2 minutes to set up :-)

**Comment by Thrilleratplay** [comment]
@SteveOnorato Thank you for letting me know about that.  Not sure if you knew, but there is also a badge to show the status.  For your component I believe it would be:

```
![hassfest_badge](https://github.com/SteveOnorato/moat_temp_hum_ble/actions/workflows/hassfest.yaml/badge.svg)
```
