### ISSUE TITLE
Automatically adding Govee Temp Senors - Feature Request

### ISSUE THREAD

**Issue by xlogik** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#35]
Since the Govee Temp Sensors have the same starting series of alphanumeric characters in the MAC address (A4:C1:38) during the scan for BLE devices, the app could automatically add ONLY the listed devices that correspond with the MAC address  "A4:C1:38" to the user's configuration.yaml file.

**Comment by Thrilleratplay** [comment]
@xlogik Theoretically a neat idea but Govee now devices use a range of BLE chips that have different prefixes, not all unique to Govee.  Also, would MACs be excluded, say if a neighbor has one?  It is annoying set up process but unfortunately I do not see a way around it without introducing new issues.
