### ISSUE TITLE
good job but...

### ISSUE THREAD

**Issue by davidemontevecchi** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#37]
i've govee temperature 5051 used on HA by bluetooth .
the issue is that if i setup more than 8 govee on my configuration.yaml all sensors stop working (error is unknow).
If i use at least 8 the problem is not present.

**Comment by Thrilleratplay** [comment]
Currently I am running 11.  There may be a configuration error being introduced when adding the eighth, I am not sure.  Without an error, it is just speculation.  If you are using a version of HA with Supervisor, the error may be under `Supervisor->System->Log Provider-> core`.  If you find an error and still need help, as stated in the README, should be asked on [this component's Home Assistant community post](https://community.home-assistant.io/t/govee-ble-thermometer-hygrometer-sensor/166696).  I am going to close this issue.
