### ISSUE TITLE
Integration crashed due the socket being unavailable

### ISSUE THREAD

**Issue by BeckmaR** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#39]
It's me again :) thanks to your last fix in #36, my sensor ran for a few days straight, until it crashed again, thanks to:
```
2021-04-04 06:20:01 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/govee_ble_hci/sensor.py", line 190, in update_ble_loop
    adapter.start_scanning()
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 279, in start_scanning
    self.set_scan_enable(False)
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 135, in set_scan_enable
    self.write_buffer(cmd)
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 51, in write_buffer
    self._socket.send(data)
OSError: [Errno 100] Network is down
```
I have no idea how this could even happen but I guess spurious errors could happen all the time. Right now, the only option to fix this is to restart home assistant. Would it be possible to wrap this in a `try / except`, catch this exception, retry and keep the integration alive?

**Comment by Thrilleratplay** [comment]
This would be related to your configuration.  The component cannot access the Bluetooth controller likely due it being blocked by another component using Bluetooth.  At this point I can only suggest removing any other Home Assistant Bluetooth related component or integration or purchase a separate Bluetooth dongle dedicated to this component.  I am looking into replacing the Bluetooth library uses but that will take a considerable amount of time develop and test.

As this seems to be configuration related, as stated in the README, should be asked on [this component's Home Assistant community post](https://community.home-assistant.io/t/govee-ble-thermometer-hygrometer-sensor/166696)

**Comment by BeckmaR** [comment]
No, it only crashed after some time after it worked previously, and I have no other Bluetooth components or integrations in use.

**Comment by Thrilleratplay** [comment]
Right, it is a race condition caused when this component cannot connect to the Bluetooth controller due to another process using it.  It may not be instantaneous as it would only occur when both are working at the same time.  There may be something trying to pair with your Home Assistant device, I am not sure.  However, due to the blocking nature of the library this component uses, the Bluetooth related process will need to be stopped.
