### ISSUE TITLE
How can I help to add compatibility to the H5055 Thermometer?

### ISSUE THREAD

**Issue by liquidbear99** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#40]

**Comment by Thrilleratplay** [comment]
See #14.  The current issue is this component doesn't decouple temperature and humidity.  You can try [natekspencer/hacs-govee_ble](https://github.com/natekspencer/hacs-govee_ble) which already does this.  I am working to implement many of these features but it will take time.  

Even afterward, I think a meat thermometer is too different of a device and should be its own component.  You are more than welcome to fork this component to implement the H5055.
