### ISSUE TITLE
H5179 Wifi

### ISSUE THREAD

**Issue by tgambee** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#41]
Will the model H5179 be supported through Wifi eventually?  I have that model and came here to see it is only ble (for now?).

**Comment by Thrilleratplay** [comment]
This is only BLE and will be for the foreseeable future.  You may want to look at #30 as it seems the Govee Wifi sends packets to its server via simple HTTP.  That is a security headache I do have the time to deal with.

**Comment by tgambee** [comment]
Thanks for the info!

Tony Gambee Latitude Digital m: 248-787-6898 a: Colorado | Michigan w: latitudedigital.com ( http://latitudedigital.com/ ) e: ***@***.***

Facebook ( http://https//www.facebook.com/tgambee ) Twitter ( http://https//twitter.com/tgambee ) Linkedin ( http://www.linkedin.com/in/tgambee/ )

This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. Latitude Software Services Inc. is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company.
