### ISSUE TITLE
Mac address?

### ISSUE THREAD

**Issue by snug-inglenook** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#44]
As there are no stupid questions: where do I find my devices Mac address?

**Comment by Thrilleratplay** [comment]
There are no stupid questions but this is not the place to ask them.  As stated in the README, qeustions should be asked on [this component's Home Assistant community post](https://community.home-assistant.io/t/govee-ble-thermometer-hygrometer-sensor/166696).  It has been asked many times and there are different ways depending on OS.  I am going to close this issue.

**Comment by avviano** [comment]
I used "BLE Scanner" which you can download at the Google Play Store (if you are using an android phone). One click and your  done!
