### ISSUE TITLE
command line/test harness

### ISSUE THREAD

**Issue by mdweisen** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#45]
This is not an issue, but a question.  Do you have any type of test setup or command-line version of the code to pull the data from a govee sensor and simply dump it out to the screen?  I'm interested in setting up a very lightweight tool to pull data very infrequently and am hoping to get to the data from my H5179 without needing to set up an entire home automation software system.

I have searched and this is the closest I have found to what I'm looking for, and I could start trying to unravel the plugin code from the data access code, but I thought I'd check to see if you have a simple example you already use to test the code that yields basically this result.

Either way, thanks for the software and thanks for reading!

**Comment by Thrilleratplay** [comment]
@mdweisen I think what you are looking for is [Thrilleratplay/GoveeWatcher](https://github.com/Thrilleratplay/GoveeWatcher).  The original project was for the H5075 but under the `debugger` is a small python wrapper for the Govee advertisement parser in this project.

**Comment by mdweisen** [comment]
Thank you... that is perfect.  Sorry to hijack the issues.

**Comment by Thrilleratplay** [comment]
@mdweisen No worries.  You actually highlighted the need to update GoveeWatcher's documentation.
