### ISSUE TITLE
Attention new version Home Assistant

### ISSUE THREAD

**Issue by Mick51** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#46]
![Capture d’écran 2022-02-06 220710](https://user-images.githubusercontent.com/40418405/152701377-40bd91b2-038e-4682-b5d2-b053e0d92bd8.jpg)

Replace the function name from "device_state_attributes" to "extra_state_attributes"

**Comment by Thrilleratplay** [comment]
@Mick51 Thank you for letting me know.  I'll look into this and should have a fix in the next few days.

**Comment by Thrilleratplay** [comment]
@Mick51 I created v10.1 beta 1.  When you have a chance, could you verify that corrects the problem?

**Comment by Mick51** [comment]
> @Mick51 I created v10.1 beta 1. When you have a chance, could you verify that corrects the problem?

Problem solved, it can pass in stable, thank you for having reacted quickly.

**Comment by Thrilleratplay** [comment]
@Mick51 Awesome.  I am going to give it another day or so in case this causes issues with older HA instances.  Again, thank you for letting me know.  There is little mention about this in recent HA releases and I guess since this is only a warning it did not flag the HASS validation.
