### ISSUE TITLE
Temperature sensor (<class 'custom_components.govee_ble_hci.sensor.TemperatureSensor'>) does not inherit SensorEntity, this will be unsupported in Home Assistant Core 2022.7.Please report it to the custom component author.

### ISSUE THREAD

**Issue by RobMatteson** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#47]
Temperature sensor (<class 'custom_components.govee_ble_hci.sensor.TemperatureSensor'>) does not inherit SensorEntity, this will be unsupported in Home Assistant Core 2022.7.Please report it to the custom component author.

**Comment by Thrilleratplay** [comment]
@RobMatteson Thank you for letting me know.  I have been very busy but I will try to update this over the weekend.

**Comment by Thrilleratplay** [comment]
@RobMatteson I created v0.10.2_beta if you or anyone else wants to test.

**Comment by RobMatteson** [comment]
@Thrilleratplay I just updated to v0.10.2_beta and restarted Home Assistant. I don't see any of the above errors anymore. I'll keep an eye on it and let you know if I run into any issues.

**Comment by Thrilleratplay** [comment]
@RobMatteson Thank you for letting me know about the warning and testing the change.  

v0.10.2 has been released.  I made a note about possibly needing to change the unit of measurement entities if display in Fahrenheit.
