### ISSUE TITLE
unpack error - measurements not stored

### ISSUE THREAD

**Issue by codestu12** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#5]
I noticed my last device measurements were 3 days old and I had the following error in the developer logs tab:

>  'Error' doing job: Future exception was never retrieved
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/home/homeassistant/.homeassistant/custom_components/govee_ble_hci/sensor.py", line 489, in update_ble
>     discover_ble_devices(config)
>   File "/home/homeassistant/.homeassistant/custom_components/govee_ble_hci/sensor.py", line 471, in discover_ble_devices
>     for mac, sensors in sensors_by_mac:
> ValueError: too many values to unpack (expected 2)

I assume this was meant to be `mac, sensors = sensors_by_mac.items()` ?

On a related topic, is there a way to flag stale measurements? I couldn't find anything suitable in the docs. If there are no measurements then you get a 'not available' message where the value would be on the UI but it doesn't seem like that can be explicitly triggered.

**Comment by codestu12** [comment]
Also in the line immediately under that `sensors.length` should be `len(sensors)`

**Comment by codestu12** [comment]
To avoid breaking stuff in the future I would recommend that what you are currently using the master branch for should really be on a develop branch and the master branch be for tested and tagged releases. It seems like HACS tracks the master branch by default and new commits are flagged as integrations that need to be upgraded when in this instance its not as stable as HACS is assuming.

**Comment by Thrilleratplay** [comment]
@codestu12   This isn't due to development.  I merged in a PR that fixed the data being saved a few dozen times a minute, then cleaned up the syntax.  I have been distracted with other things going on and haven't been paying attention to this as closely as I should.  I apologize and will do my best not to push any more breaking changes.  I'm look into this now and should have an update soon.  Again, sorry for this.

**Comment by Thrilleratplay** [comment]
@codestu12  Fixed.

**Comment by codestu12** [comment]
No worries. I appreciate the work you are putting in. Do you want me do pull requests for this and any other things I find or do you prefer to handle them yourself?

**Comment by Thrilleratplay** [comment]
@codestu12  This has been fixed in the latest update.  Pull requests are always appreciated but do not expect others to fix my mistakes.
